# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "txTrABga8GfbW/1S7mLJh7I82CINnwsI9hndnZxSx6K5419iG6oO92WfqiIP/ldxZ9AxMdRvpEbPHFNP5q8ebXtAtpY+ic4ZCpINLkXFlaLIccH+uMQvDXdn2DOhcDAJCfvKhSir4s07BwVu0I5y/w5Jzzp78+8MWOeQ6dvlrqE4l7WCluz8Bzono6zBZj7oU2EZCFGyKwuHRsxEE7YQODorunpn6J4/UfBcD0e0qnvXAPRYSJq6PIxrHfRZMksOFUrXjMoN9B2nWJ17e/cVXUXi+mwxw/veNpnjSRPpWs1NXyWKwpqT+FTKpjw3CPLcRpqdfEGmMFibZ4WeH/+/K47cxQxyRGNbfEtiYodn7v5IUsmJsZbOJ1Nl630yB2M7mu/jeE6oO7lnnKWZXi15lthzbvWVC7VzPjT9K5LViMeBTSENFCzIPH8nAhDiI0AlDVfgVdlRas779VpHr7QL+06TkVB4u4KhSdiLHz6a8i4PcDX2UXp+JvmWCj7+p3OFOa8AW4QaZ96cHK5zh4Rtq5Otmnjp2gTjhTZG+p+8k41KeJgh0Ji+qNl+huXOZhTJ7eIOnMT8fHxcvhDSleoeTIs1yA1thzgnnP3vOtNSiN8JniwM85S+2pr+Yk+RmLZrVBzOfmrQIAjSs/o6kPv3EbeESbRlFFYwhFQQePBqtCs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
