travis:
  secure:
    BINSTAR_TOKEN: txTrABga8GfbW/1S7mLJh7I82CINnwsI9hndnZxSx6K5419iG6oO92WfqiIP/ldxZ9AxMdRvpEbPHFNP5q8ebXtAtpY+ic4ZCpINLkXFlaLIccH+uMQvDXdn2DOhcDAJCfvKhSir4s07BwVu0I5y/w5Jzzp78+8MWOeQ6dvlrqE4l7WCluz8Bzono6zBZj7oU2EZCFGyKwuHRsxEE7YQODorunpn6J4/UfBcD0e0qnvXAPRYSJq6PIxrHfRZMksOFUrXjMoN9B2nWJ17e/cVXUXi+mwxw/veNpnjSRPpWs1NXyWKwpqT+FTKpjw3CPLcRpqdfEGmMFibZ4WeH/+/K47cxQxyRGNbfEtiYodn7v5IUsmJsZbOJ1Nl630yB2M7mu/jeE6oO7lnnKWZXi15lthzbvWVC7VzPjT9K5LViMeBTSENFCzIPH8nAhDiI0AlDVfgVdlRas779VpHr7QL+06TkVB4u4KhSdiLHz6a8i4PcDX2UXp+JvmWCj7+p3OFOa8AW4QaZ96cHK5zh4Rtq5Otmnjp2gTjhTZG+p+8k41KeJgh0Ji+qNl+huXOZhTJ7eIOnMT8fHxcvhDSleoeTIs1yA1thzgnnP3vOtNSiN8JniwM85S+2pr+Yk+RmLZrVBzOfmrQIAjSs/o6kPv3EbeESbRlFFYwhFQQePBqtCs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
