travis:
  secure:
    BINSTAR_TOKEN: AakiHJPbvkK/ZlmvbBxGg7lt7OelbrSn0ys5Ndop3CTEbfkKXuiy6UY5K0JuN73Uoom9j65s6wKDIaNjoao1ECru0lVqpEl8WNacC8BiGHiK2CISvINVY0OExt/u83o+r4awdAeqBQI99kYK3g2PIKrX/sNdhA1yiLD2m2pOelWZOUsZOSypLUxf+VxCoLYbRbxdJniXbeJk88wnGox0JllZ8qRHJPOzjPWWTapuWLs3OGpm19ghH5yCkGVuVEjnQLL9UWauJmXO82Wh7tj/JVhZDy+q95ZoGGG4cxC/jZpOdqIbazd4VPH47IbHbQB0S1+MltcPVhqhDc2VZWKqkSRd95mOypZ7S0F0S7S8Us6ABpy6HHCgot71HcNjQKIDzdYDxXmkMpGHuEcBGenvBwMCqnnewuQOkzdmV3twu/gHoWtNCRgpCaUJj8kb8jc9EFH+GB35oRXkyCuyZ5xHhde81PjfEc3vLqncnhKW/EEVBKjFXXvGNvhH4MG8FeIqb/ExYvbe9zWdrJsYkR1SUeIkEU4OIkup0ciZQNQNBDtLjD2B/Q4gkRvPROUfKuUEPXhXOzM933CuDaoiI6sy6tHIkRdyzcxo/Uf5txMjFPfVnoz60ZggJlDkgmDOxjp1Y8lv/GGJEsQ4QtqRjTaMNyIwcqW9dY7cmH1UHAg+Zas=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
